# Generated by Django 4.2.16 on 2024-11-04 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Solicitudes', '0002_alter_solicitud_presupuesto_precio'),
        ('Notificaciones', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificacion',
            name='mensaje',
        ),
        migrations.AddField(
            model_name='notificacion',
            name='solicitud',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Solicitudes.solicitud_presupuesto'),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='tipo_notificacion',
            field=models.CharField(choices=[('Solicitud de Presupuesto', 'Solicitud de Presupuesto'), ('Confirmacion de Pago', 'Confirmacion de Pago'), ('Respuesta de Solicitud', 'Respuesta de Solicitud'), ('Calificar Servicio', 'Calificar Servicio')], max_length=100),
        ),
    ]
