# Generated by Django 4.2.16 on 2024-10-29 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Usuarios', '__first__'),
        ('Servicios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contratacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado_transaccion', models.CharField(choices=[('pendiente', 'Pendiente'), ('completada', 'Completada')], max_length=20)),
                ('fecha_contratacion', models.DateField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuarios.cliente')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Servicios.servicio')),
            ],
        ),
    ]
