# Generated by Django 4.2.16 on 2024-10-29 02:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('categoria', models.CharField(max_length=255)),
                ('direccion', models.CharField(max_length=500)),
                ('precio_minimo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_maximo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('informacion_detallada', models.TextField()),
                ('promedio_calificacion', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuarios.proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='Imagenes_Servicios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='servicios/')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='Servicios.servicio')),
            ],
        ),
    ]
