# Generated by Django 4.2.16 on 2024-11-05 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Usuarios', '0001_initial'),
        ('Servicios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitud_Presupuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_evento', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('duracion', models.FloatField()),
                ('personas', models.IntegerField()),
                ('direccion', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada')], max_length=20)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuarios.cliente')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuarios.proveedor')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Servicios.servicio')),
            ],
        ),
    ]
